version: "3.8"

services:
  archaeologist:
    build:
      context: ./
      target: production
    command:
      - /bin/bash
      - -c
      - |
        npm run peer-id-gen
        npm run cli start
    environment:
      FORCE_COLOR: 1