version: "3.8"

services:
  archaeologist:
    build:
      context: ./
      target: production
    command:
      - /bin/bash
      - -c
      - |
        npm run peer-id-gen
        npm run cli start
    volumes:
      - type: bind
        source: ./peer-id.json
        target: /peer-id.json
    environment:
      FORCE_COLOR: 1