name: publish
on: [ push ]
jobs:
  publish-hello-docker-image:
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v3
    - name: Login to GitHub Container Registry
  uses: docker/login-action@v1
  with:
    registry: ghcr.io
    username: ${{ github.actor }}
    password: ${{ secrets.GITHUB_TOKEN }}
                - name: Build the archaeologist-service Docker image
  run: |
    docker build . --tag ghcr.io/sarcophagus-org/archaeologist-service:latest
    docker push ghcr.io/sarcophagus-org/archaeologist-service:latest